baseURL = "https://dreger.me/"
languageCode = "en-us"
title = "K.Q. Dreger"
uglyurls = true
publishDir = "docs"
[permalinks]
	notes = "/notes/:filename"
	links = "/links/:filename"
	pages = "/:filename"
